import type { Metadata } from "next"
import "./globals.css"
import { Nunito } from "next/font/google"
import type { FC, ReactNode } from "react"

const nunito = Nunito({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

interface RootLayoutProps {
	children: ReactNode
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang="en" className={nunito.className}>
			<body>{children}</body>
		</html>
	)
}

export default RootLayout
